task:
  pipeline:
    config:
      zkConnectStr: 127.0.0.1:2181
      sessionTimeout: 3600000
      baseSleepTimeMs: 0
      maxRetries: 5
      corePoolSize: 5
      maxthreadPoolSize: 10
      keepApiveTime: 0
      queueSize: 20
      aclIds:
        - tp_server:^zskxtpserver123456
        - tp_app:^zskxtpapp123456
        - tp_worker:^zskxtpworker123456
      aclId: tp_server:^zskxtpserver123456
logging:
  path: log/
server:
  port: 8888
